---
# install redis server

- name: Make sure EPEL repo is installed
  yum:
    name: epel-release
    state: installed
  tags: [redis]

- name: Installing redis server
  yum:
    name: redis
    state: installed
  notify: restart redis
  tags: [redis]

- name: Enabling redis server
  service:
    name: redis
    enabled: yes
  notify: restart redis
  tags: [redis]

- name: Enabling sentinel
  service:
    name: redis-sentinel
    enabled: yes
  notify: restart sentinel
  when: replication
  tags: [redis, sentinel]

- name: Create /var/lib/redis/sentinel
  file:
    state: directory
    path: '/var/lib/redis/sentinel'
    owner: redis
    group: redis
    mode: 0755
  notify: restart sentinel
  when: replication
  tags: [redis, sentinel]

- name: Adjust net.core.somaxconn to 65535
  lineinfile:
    line: 'net.core.somaxconn=65535'
    path: /etc/sysctl.conf
    state: present
    insertafter: EOF
  notify:
    - 'restart sentinel'
    - 'restart redis'
    - 'sysctl'
  when: replication
  tags: [redis, sentinel]

- name: Configure redis-sentinel (/etc/redis-sentinel.conf)
  template:
    src: redis-sentinel.conf.j2
    dest: /etc/redis-sentinel.conf
    owner: redis
    group: root
    mode: 0640
  notify: restart sentinel
  when: replication
  tags: [redis, sentinel]

- name: Configure redis (/etc/redis.conf)
  template:
    src: redis.conf.j2
    dest: /etc/redis.conf
    owner: redis
    group: root
    mode: 0640
  notify: restart redis
  when: replication
  tags: [redis, sentinel]
