---

- name: Install Redis server
  yum:
    name: redis
    state: installed
  notify: restart redis
  tags: [redis]

- name: Enable Redis server
  service:
    name: redis
    enabled: yes
  notify: restart redis
  tags: [redis]

- name: Enable Sentinel
  service:
    name: redis-sentinel
    enabled: yes
  notify: restart sentinel
  when: replication
  tags: [redis, sentinel]

- name: Create /var/lib/redis/sentinel
  file:
    state: directory
    path: '/var/lib/redis/sentinel'
    owner: redis
    group: redis
    mode: 0755
  notify: restart sentinel
  when: replication
  tags: [redis, sentinel]

- name: Configure redis-sentinel (/etc/redis-sentinel.conf)
  template:
    src: redis-sentinel.conf.j2
    dest: /etc/redis-sentinel.conf
    owner: redis
    group: root
    mode: 0640
  notify: restart sentinel
  when: replication
  tags: [redis, sentinel]

- name: Configure Redis (/etc/redis.conf)
  template:
    src: redis.conf.j2
    dest: /etc/redis.conf
    owner: redis
    group: root
    mode: 0640
  notify: restart redis
  when: replication
  tags: [redis, sentinel]

- name: Adjust net.core.somaxconn to 65535
  sysctl:
    name: net.core.somaxconn
    value: 65535
    state: present
  notify:
    - 'restart sentinel'
    - 'restart redis'
